title: PS-Jsonify Docs
description: Documentation site for PS-Jsonify
baseurl: "/ps-jsonify" # the subpath of your site, e.g. /blog
url: "https://coltonfischer.com" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pmarsceill/just-the-docs
